import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Default.module.css";
import Image from "next/image";
import sample from "../public/sampleApps.png";
import sampleApps from "../public/sampleApps2.png";

const LeftDefault = (props) => {
    const router = useRouter()
    const toHome = () => {
        router.push("/")
    }

  return (
    <>
      <Head>
        <title>Zwallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container-fluid">
        <div className="row">
          <div className={`col-lg-7 ${styles.contentDefault}`}>
            <div className="row">
              <div onClick={toHome} className="col-lg-12">
                <h2 className={styles.titleLeft}>Zwallet</h2>
              </div>
              <div className="col-lg-12 text-center">
                <Image
                  src={sample}
                  alt="sample1"
                  width={279}
                  height={547}
                  className={`position-absolute ${styles.sample}`}
                />
                <Image
                  src={sampleApps}
                  alt="sample1"
                  width={279}
                  height={547}
                  className={`${styles.sample2}`}
                />
              </div>
              <div className="col-lg-12 mt-lg-3">
                <div className="row d-flex justify-content-center">
                  <div className="col-lg-10">
                    <h5 className={`${styles.footerDef}`}>
                      App that Covering Banking Needs.
                    </h5>
                  </div>
                  <div className="col-lg-10">
                    <small className={`${styles.noteDef}`}>
                      Zwallet is an application that focussing in banking needs
                      for all users in the world. Always updated and always
                      following world trends. 5000+ users registered in Zwallet
                      everyday with worldwide users coverage.
                    </small>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="col-lg-5">{props.children}</div>
        </div>
      </div>
    </>
  );
};

export default LeftDefault;
