/* eslint-disable react-hooks/rules-of-hooks */
import React, { useState } from "react";
import Sidebar from "../../layout/sidebar";
import styles from "../../styles/Success.module.css";
import Image from "next/image";
import profile from "../../public/profile.png";
import { useRouter } from "next/router";
import { Button, ButtonGroup, ButtonToolbar } from "reactstrap";
import { AiOutlineCheck } from "react-icons/ai";
import Head from "next/head";
import NavbarApps from "../../components/Navbar";
import FooterApps from "../../components/Footer";
// import stylesSide from "../styles/Sidebar.module.css"
import { BsGrid, BsPerson } from "react-icons/bs";
import { RiArrowUpLine } from "react-icons/ri";
import { AiOutlinePlus, AiOutlineDownload } from "react-icons/ai";
import { FiLogOut, FiShare2 } from "react-icons/fi";

const success = () => {
  const receiver = {
    name: "Samuel Suhi",
    phone: "+62 813-8492-9994",
    total: 50000,
  };

  const infoTf = {
    amount: 100000,
    balanceLeft: 20000,
    date: "May 11, 2020 - 12.20",
    notes: "For buying some socks",
  };

  const router = useRouter();

  const toDashboard = () => {
    router.push("/home");
  };

  const toTransfer = () => {
    router.push("/transfer");
  };

  const toTopup = () => {
    router.push("/topup")
  }

  const toProfile = () => {
    router.push("/profile")
  }
  
  const toHomePage = () => {
    router.push("/")
  }

  return (
    <>
      <Head>
        <title>Zwallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <NavbarApps />

        <div className={`container-fluid ${styles.content}`}>
          <div className="row">
            <div className="col-lg-3 d-flex justify-content-end me-5">
              <div className={`${styles.sidebar}`}>
                <ul className="navbar-nav">
                  <li
                    onClick={toDashboard}
                    className={`nav-item my-4 d-flex align-items-center ${styles.navItem}`}
                  >
                    <BsGrid size={28} />
                    <span className="links_name ms-4">Dashboard</span>
                    <span className="tooltip">Dashboard</span>
                  </li>

                  <li
                    onClick={toTransfer}
                    className={`nav-item my-4 d-flex align-items-center  ${styles.navItem}`}
                  >
                    <RiArrowUpLine size={28} />
                    <span className="links_name ms-4">Transfer</span>

                    <span className="tooltip">Transfer</span>
                  </li>

                  <li
                  onClick={toTopup}
                    className={`nav-item my-4 d-flex align-items-center ${styles.navItem}`}
                  >
                    <AiOutlinePlus size={28} />
                    <span className="links_name ms-4">Top Up</span>
                    <span className="tooltip">Top Up</span>
                  </li>

                  <li
                    onClick={toProfile}
                    className={`nav-item my-4 d-flex align-items-center ${styles.navItem}`}
                  >
                    <BsPerson size={28} />
                    <span className="links_name ms-4">Profile</span>
                    <span className="tooltip">Profile</span>
                  </li>

                  <li
                    onClick={toHomePage}
                    className={`nav-item d-flex align-items-center ${styles.navItemLogout}`}
                  >
                    <FiLogOut size={28} />
                    <span className="links_name ms-4">Log out</span>
                    <span className="tooltip">Log out</span>
                  </li>
                </ul>
              </div>
            </div>

            <div className="col-lg-8">
              <div className={`row ${styles.successContent}`}>
                <div className={`col-lg-12 d-flex justify-content-center mt-3`}>
                  <div className={`${styles.packHead}`}>
                    <div className={` ${styles.titleSuccess}`}>
                      <AiOutlineCheck size={32} />
                    </div>
                    <div className="mt-2">
                      <small className={`${styles.noteSuccess}`}>
                        Transfer Success
                      </small>
                    </div>
                  </div>
                </div>
                <div className={`col-lg-12 ${styles.infoContent}`}>
                  <div className={`row mb-3 ${styles.cardContact}`}>
                    <div className="col-lg-9">
                      <div>
                        <p className={`${styles.titleCardInfo}`}>Amount</p>
                        <p className={`${styles.bodyCardInfo}`}>
                          {infoTf.amount}
                        </p>
                      </div>
                    </div>
                  </div>

                  <div className={`row mb-3 ${styles.cardContact}`}>
                    <div className="col-lg-9">
                      <div>
                        <p className={`${styles.titleCardInfo}`}>
                          Balance left
                        </p>
                        <p className={`${styles.bodyCardInfo}`}>
                          {infoTf.balanceLeft}
                        </p>
                      </div>
                    </div>
                  </div>

                  <div className={`row mb-3 ${styles.cardContact}`}>
                    <div className="col-lg-9">
                      <div>
                        <p className={`${styles.titleCardInfo}`}>Date & Time</p>
                        <p className={`${styles.bodyCardInfo}`}>
                          {infoTf.date}
                        </p>
                      </div>
                    </div>
                  </div>

                  <div className={`row mb-3 ${styles.cardContact}`}>
                    <div className="col-lg-9">
                      <div>
                        <p className={`${styles.titleCardInfo}`}>Notes</p>
                        <p className={`${styles.bodyCardInfo}`}>
                          {infoTf.notes}
                        </p>
                      </div>
                    </div>
                  </div>
                </div>{" "}
                {/*  infoContent */}
                <div className={`${styles.titleTfto}`}>
                  <p>Transfer to</p>
                </div>
                <div className="d-flex flex-column justify-content-center align-items-center">
                  <div className={`row ${styles.cardContactReceiver}`}>
                    <div className="col-lg-9">
                      <div className="row">
                        <div className="col-lg-2">
                          <Image
                            src={profile}
                            alt="profile"
                            className={`${styles.imageProfileReceiver}`}
                            width={70}
                            height={70}
                          />
                        </div>

                        <div
                          className={`col-lg-8 d-flex flex-column ${styles.infoReceiver}`}
                        >
                          <span className={`${styles.nameProfileNav}`}>
                            {receiver.name}
                          </span>
                          <small className={`${styles.statusTrans}`}>
                            {receiver.phone}
                          </small>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="d-flex justify-content-end align-items-center">
                  {/* <ButtonGroup className="me-5"> */}
                    <Button onClick={toDashboard} className={`me-3 ${styles.btnShare}`}>
                      <FiShare2 size={28} />
                    </Button>
                    <Button onClick={toDashboard} className={`mx-3 ${styles.btnDwld}`}>
                      <AiOutlineDownload size={28} className="me-3" />
                      <small>Download PDF</small>
                    </Button>
                    <Button onClick={toDashboard} className={`ms-3 me-5 ${styles.backToHome}`}>
                      Back To Home
                    </Button>
                  {/* </ButtonGroup> */}
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className={`${styles.footerSuccess}`}>
          <FooterApps />
        </div>
      </div>
    </>
  );
};

export default success;
