/* eslint-disable react-hooks/rules-of-hooks */
import React, { useState } from "react";
import styles from "../../styles/Topup.module.css";
import { useRouter } from "next/router";
import { Button } from "reactstrap";
import Head from "next/head";
import NavbarApps from "../../components/Navbar";
import FooterApps from "../../components/Footer";
import { BsGrid, BsPerson } from "react-icons/bs";
import { RiArrowUpLine } from "react-icons/ri";
import { AiOutlinePlus } from "react-icons/ai";
import { FiLogOut } from "react-icons/fi";

const Topup = () => {
  const procedures = [
    {
      id: 1,
      procedure: "Go to the nearest ATM or you can use E-Banking.",
    },
    {
      id: 2,
      procedure: "Type your security number on the ATM or E-Banking.",
    },
    {
      id: 3,
      procedure: "Select “Transfer” in the menu",
    },
    {
      id: 4,
      procedure:
        "Type the virtual account number that we provide you at the top.",
    },
    {
      id: 5,
      procedure: "Type the amount of the money you want to top up.",
    },
    {
      id: 6,
      procedure: "Read the summary details",
    },
    {
      id: 7,
      procedure: "Press transfer / top up",
    },
    {
      id: 8,
      procedure: "You can see your money in Zwallet within 3 hours.",
    },
  ];

  const receiver = {
    name: "Samuel Suhi",
    phone: "+62 813-8492-9994",
    total: 50000,
  };

  const infoTf = {
    amount: 100000,
    balanceLeft: 20000,
    date: "May 11, 2020 - 12.20",
    notes: "For buying some socks",
  };

  const router = useRouter();

  const toDashboard = () => {
    router.push("/home");
  };

  const toTransfer = () => {
    router.push("/transfer");
  };

  const toTopup = () => {
    router.push("/topup")
  }
  
  const toProfile = () => {
    router.push("/profile")
  }
  
  const toHomePage = () => {
    router.push("/")
  }

  return (
    <>
      <Head>
        <title>Zwallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <NavbarApps />

        <div className={`container-fluid ${styles.content}`}>
          <div className="row">
            <div className="col-lg-3 d-flex justify-content-end me-5">
              <div className={`${styles.sidebar}`}>
                <ul className="navbar-nav">
                  <li
                    onClick={toDashboard}
                    className={`nav-item my-4 d-flex align-items-center ${styles.navItem}`}
                  >
                    <BsGrid size={28} />
                    <span className="links_name ms-4">Dashboard</span>
                    <span className="tooltip">Dashboard</span>
                  </li>

                  <li
                    onClick={toTransfer}
                    className={`nav-item my-4 d-flex align-items-center  ${styles.navItem}`}
                  >
                    <RiArrowUpLine size={28} />
                    <span className="links_name ms-4">Transfer</span>

                    <span className="tooltip">Transfer</span>
                  </li>

                  <li
                    onClick={toTopup}
                    className={`nav-item my-4 d-flex align-items-center ${styles.navItem}`}
                  >
                    <AiOutlinePlus size={28} />
                    <span className="links_name ms-4">Top Up</span>
                    <span className="tooltip">Top Up</span>
                  </li>

                  <li
                    onClick={toProfile}
                    className={`nav-item my-4 d-flex align-items-center ${styles.navItem}`}
                  >
                    <BsPerson size={28} />
                    <span className="links_name ms-4">Profile</span>
                    <span className="tooltip">Profile</span>
                  </li>

                  <li
                    onClick={toHomePage}
                    className={`nav-item d-flex align-items-center ${styles.navItemLogout}`}
                  >
                    <FiLogOut size={28} />
                    <span className="links_name ms-4">Log out</span>
                    <span className="tooltip">Log out</span>
                  </li>
                </ul>
              </div>
            </div>

            <div className="col-lg-8">
              <div className={`row ${styles.successContent}`}>
                <div className={`col-lg-12 ms-3 mt-3`}>
                  <div className={`${styles.packHead}`}>
                    <div className="mt-2">
                      <small className={`${styles.noteSuccess}`}>
                        How To Top Up
                      </small>
                    </div>
                  </div>
                </div>

                <div className={`col-lg-12 ${styles.infoContent}`}>
                  {procedures.map((e, i) => (
                    <div
                      key={i}
                      className={`row mb-3 ${styles.cardProcedures}`}
                    >
                      <div className="col-lg-1 text-center">
                        <p className={`${styles.noProced}`}>{e.id}</p>
                      </div>
                      <div className="col-lg-9">
                        <div>
                          <p className={`${styles.bodyCardInfo}`}>
                            {e.procedure}
                          </p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>

                <div className="row g-3 justify-content-center align-items-center" style={{marginTop: "-30px"}}>
                  <div className="col-auto">
                    <label className={`col-form-label ${styles.labelNominal}`}>Rp</label>
                  </div>
                  <div className="col-auto">
                    <input 
                    type="number"
                    className={`form-control ${styles.inputNominal}`} 
                    placeholder="0.00" />
                  </div>
                  <div className="col-auto">
                    <Button
                    //   onClick={toDashboard}
                      className={`ms-3 me-5 ${styles.btnTopup}`}
                    >
                      Top Up
                    </Button>
                  </div>
                </div>
                
              </div>
            </div>
          </div>
        </div>

        <div className={`${styles.footerSuccess}`}>
          <FooterApps />
        </div>
      </div>
    </>
  );
};

export default Topup;
