import { useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { BsTelephone } from "react-icons/bs";
import { FiLock } from "react-icons/fi";
import { AiOutlineDownload } from "react-icons/ai";
import sampleApps from "../public/sampleApps.png";
import airbnb from "../public/airbnb.png";
import canon from "../public/canon.png";
import dell from "../public/dell.png";
import microsoft from "../public/microsoft.png";
import dropbox from "../public/dropbox.png";
import hm from "../public/h&m.png";


export default function Home() {

  const router = useRouter()

  const [partner, setPartner] = useState([
    {
      imageUrl: airbnb,
    },
    {
      imageUrl: canon,
    },
    {
      imageUrl: dell,
    },
    {
      imageUrl: microsoft,
    },
    {
      imageUrl: dropbox,
    },
    {
      imageUrl: hm,
    },
  ]);

  const login = () => {
    router.push('/login')
  }

  const signup = () => {
    router.push('/signup')
  }

  return (
    <div>
      <Head>
        <title>Zwallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container-fluid">
        <div className="row">
          <div className={`col-lg-6 ${styles.contentLeft}`}>
            <div className="row">
              <div className={`col-lg-12 ${styles.titleApps}`}>
                <div className="row">
                  <div className="col-lg-12 col-4">
                    <h4 className="ms-lg-5 ms-3 mt-4">Zwallet</h4>
                  </div>

                  {/* btn d-block on mobile */}
                  <div className="d-lg-none d-block col-8">
                    <div
                      className={`d-grid gap-2 d-flex mt-3 justify-content-end ${styles.btnGroupSm}`}
                    >
                      <button
                        className={`btn me-lg-2 ${styles.btnLoginSm}`}
                        type="button"
                        onClick={login}
                      >
                        Login
                      </button>
                      <button
                        className={`btn ${styles.btnSignUpSm}`}
                        type="button"
                        onClick={signup}
                      >
                        Sign Up
                      </button>
                    </div>
                  </div>
                </div>
              </div>

              <div className="col-lg-12 ms-lg-5">
                <div className="row">
                  <div className={`col-lg-7  ${styles.jumbotronPack}`}>
                    <h1 className={`${styles.jumbotronTitle}`}>
                      Awesome App For Saving{" "}
                      <span className={styles.timeTitle}>Time.</span>
                    </h1>
                  </div>
                  <div className="col-lg-7 mt-lg-4">
                    <small className={`${styles.jumbotronNote}`}>
                      We bring you a mobile app for banking problems that
                      oftenly wasting much of your times.
                    </small>
                  </div>
                  <div className="col-lg-7 mt-lg-5">
                    <button
                      type="button"
                      className={`btn ${styles.jumbotronBtn}`}
                    >
                      Try It Free
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className={`col-lg-6 ${styles.jumbotronRight}`}>
            <div className="row">
              <div className={`col-lg-12 mt-lg-4`}>
                <div
                  className={`d-grid gap-2 d-flex justify-content-end me-lg-5 ${styles.btnGroup}`}
                >
                  <button
                    className={`btn me-lg-2 ${styles.btnLogin}`}
                    type="button"
                    onClick={login}
                  >
                    Login
                  </button>
                  <button className={`btn ${styles.btnSignUp}`} type="button"
                  onClick={signup}
                  >
                    Sign Up
                  </button>
                </div>
              </div>
            </div>
            <div className={`position-absolute ${styles.sample}`}>
              <Image
                src={sampleApps}
                alt="Sample Apps"
                width={439}
                height={800}
                className={` ${styles.imgSample}`}
              />
            </div>
          </div>
        </div>

        <div className={`row ${styles.aboutCompany}`}>
          <div className={`col-lg-12 mt-5`}>
            <div className={`row  ${styles.packTitle}`}>
              <div className={`col-lg-10 text-center ${styles.titleAbout}`}>
                <h1>About the Application.</h1>
              </div>
              <div
                className={`col-lg-4 mt-lg-3 text-center ${styles.noteAbout}`}
              >
                <small>
                  We have some great features from the application and it’s
                  totally free to use by all users around the world.
                </small>
              </div>
            </div>
          </div>
          <div className="col-lg-12">
            <div className={`row  ${styles.aboutApps}`}>
              <div className={`col-lg-4 col-5 p-5 ${styles.aboutSupport}`}>
                <div className="row">
                  <div className={`col-lg-12 d-flex justify-content-center`}>
                    <div className={`p-3 ${styles.iconRounded}`}>
                      <BsTelephone size={28} />
                    </div>
                  </div>

                  <div
                    className={`col-lg-12 mt-3 d-flex justify-content-center`}
                  >
                    <div className={`${styles.titleSupport}`}>
                      <p>24/7 Support</p>
                    </div>
                  </div>

                  <div className={`col-lg-12 d-flex justify-content-center`}>
                    <div className={`p-3 ${styles.noteSupport}`}>
                      <small>
                        We have 24/7 contact support so you can contact us
                        whenever you want and we will respond it.
                      </small>
                    </div>
                  </div>
                </div>
              </div>

              <div className={`col-lg-4 col-5 p-5 ${styles.aboutSupport}`}>
                <div className="row">
                  <div className={`col-lg-12 d-flex justify-content-center`}>
                    <div className={`p-3 ${styles.iconRounded}`}>
                      <FiLock size={28} />
                    </div>
                  </div>

                  <div
                    className={`col-lg-12 mt-3 d-flex justify-content-center`}
                  >
                    <div className={`${styles.titleSupport}`}>
                      <p>Data Privacy</p>
                    </div>
                  </div>

                  <div className={`col-lg-12 d-flex justify-content-center`}>
                    <div className={`p-3 ${styles.noteSupport}`}>
                      <small>
                        We make sure your data is safe in our database and we
                        will encrypt any data you submitted to us.
                      </small>
                    </div>
                  </div>
                </div>
              </div>

              <div className={`col-lg-4 col-5 p-5 ${styles.aboutSupport}`}>
                <div className="row">
                  <div className={`col-lg-12 d-flex justify-content-center`}>
                    <div className={`p-3 ${styles.iconRounded}`}>
                      <AiOutlineDownload size={28} />
                    </div>
                  </div>

                  <div
                    className={`col-lg-12 mt-3 d-flex justify-content-center`}
                  >
                    <div className={`${styles.titleSupport}`}>
                      <p>Easy Download</p>
                    </div>
                  </div>

                  <div className={`col-lg-12 d-flex justify-content-center`}>
                    <div className={`p-3 ${styles.noteSupport}`}>
                      <small>
                        Zwallet is 100% totally free to use it’s now available
                        on Google Play Store and App Store.
                      </small>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className={`row mt-lg-5 ${styles.partner}`}>
          <div className="col-lg-5">
            <div className="row">
              <div className="col-lg-7">
                <h2 className={`${styles.titlePartner}`}>
                  100+ <span className={styles.timeTitle}>Trusted</span>{" "}
                  Partners.
                </h2>
              </div>
              <div className={`col-lg-6 mt-lg-3 ${styles.noteAbout}`}>
                <small>
                  We have reached global level and have 100+ brand partners
                  around the globe.
                </small>
              </div>
            </div>
          </div>
          <div className="col-lg-5 d-lg-block d-none">
            <div className="row">
              {partner.map((e, i) => (
                <div key={i} className={`col-lg-4 my-4 `}>
                  <Image
                    src={e.imageUrl}
                    width={150}
                    height={80}
                    className={`${styles.imgPartner}`}
                    alt="partner"
                  />
                </div>
              ))}
            </div>
          </div>
        </div>

        <footer className={`row ${styles.footerApps}`}>
          <div className="col-lg-12">
            <div className="row pb-lg-5 border-bottom">
              <div className="col-lg-12">
                <h1 className={`${styles.titleFoot}`}>Zwallet</h1>
              </div>
              <div className="col-lg-2 ">
                <p className={`${styles.noteFoot}`}>Simplify financial needs and saving much time in banking needs with one single app.</p>
              </div>
            </div>
            <div className={`row mt-lg-3 ${styles.noteFoot}`}>
              <div className="col-lg-4">
                <small>2020 Zwallet. All right reserved.</small>
              </div>
              <div className="col-lg-8 text-end">
                    <small className="me-5">+62 5637 8882 9901</small>
                    <small>contact@zwallet.com</small>
              </div>
            </div>
          </div>
        </footer>
      </div>
    </div>
  );
}
